// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service-content.pb

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceContent struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceContent) Reset()         { *m = ServiceContent{} }
func (m *ServiceContent) String() string { return proto.CompactTextString(m) }
func (*ServiceContent) ProtoMessage()    {}
func (*ServiceContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_687eff947ce3e6b6, []int{0}
}

func (m *ServiceContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceContent.Unmarshal(m, b)
}
func (m *ServiceContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceContent.Marshal(b, m, deterministic)
}
func (m *ServiceContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceContent.Merge(m, src)
}
func (m *ServiceContent) XXX_Size() int {
	return xxx_messageInfo_ServiceContent.Size(m)
}
func (m *ServiceContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceContent.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceContent proto.InternalMessageInfo

func (m *ServiceContent) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceContent)(nil), "pb.ServiceContent")
}

func init() { proto.RegisterFile("service-content.pb", fileDescriptor_687eff947ce3e6b6) }

var fileDescriptor_687eff947ce3e6b6 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x4d, 0xce, 0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0xd1, 0x2b, 0x48, 0x12, 0x62,
	0x2a, 0x48, 0x52, 0xd2, 0xe1, 0xe2, 0x0b, 0x86, 0xc8, 0x38, 0x43, 0x24, 0x84, 0xa4, 0xb8, 0x38,
	0x4a, 0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0,
	0xfc, 0x24, 0xb6, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b,
	0x29, 0x9e, 0x91, 0x4e, 0x00, 0x00, 0x00,
}
