# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sayHello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sayHello.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0esayHello.proto\x12\x02pb\"#\n\x0fSayHelloRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\"\n\x0fSayHelloReponse\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')
)




_SAYHELLOREQUEST = _descriptor.Descriptor(
  name='SayHelloRequest',
  full_name='pb.SayHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='pb.SayHelloRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=57,
)


_SAYHELLOREPONSE = _descriptor.Descriptor(
  name='SayHelloReponse',
  full_name='pb.SayHelloReponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pb.SayHelloReponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['SayHelloRequest'] = _SAYHELLOREQUEST
DESCRIPTOR.message_types_by_name['SayHelloReponse'] = _SAYHELLOREPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SayHelloRequest = _reflection.GeneratedProtocolMessageType('SayHelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLOREQUEST,
  __module__ = 'sayHello_pb2'
  # @@protoc_insertion_point(class_scope:pb.SayHelloRequest)
  ))
_sym_db.RegisterMessage(SayHelloRequest)

SayHelloReponse = _reflection.GeneratedProtocolMessageType('SayHelloReponse', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLOREPONSE,
  __module__ = 'sayHello_pb2'
  # @@protoc_insertion_point(class_scope:pb.SayHelloReponse)
  ))
_sym_db.RegisterMessage(SayHelloReponse)


# @@protoc_insertion_point(module_scope)
